[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.93.3"

[[redirects]]
  from = "/pgd"
  to = "/pgd.pdf"
  status = 301
  force = true
  query = {path = ":path"}
